# oilan/docker-compose.yml
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy 
    environment:
    # These values will be automatically read from the .env file
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    # OpenAI API key is now included in the environment variables
    #  - OPENAI_API_KEY=${OPENAI_API_KEY}
    # DB credentials are still here, which is fine for local development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=oilan_db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=oilan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U user -d oilan_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: