# oilan/docker-compose.yml
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy 
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=oilan_db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTG-RES_PASSWORD=password
      - POSTGRES_DB=oilan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U user -d oilan_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: